class AppStrings {
  AppStrings._();
  static const String title = 'Poll';
  static const String appName = 'APSEC';
  static const String footer_poweredby = "Powered by CGG";
  static const String search = "Search";
  static const internet_check =
      "No network connectivity found, please check your internet connection";
  static const String ok = 'OK';
  static const DistrictsIDs = [
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33"
  ];
  static final List<String> DistrictsEnglish = [
    "--Select--",
    "Adilabad",
    "Komaram Bheem",
    "Mancherial",
    "Nirmal",
    "Nizamabad",
    "Jagtial",
    "Peddapalli",
    "Jayashankar",
    "Bhadradri",
    "Mahabubabad",
    "Warangal Rural",
    "Warangal Urban",
    "Karimnagar",
    "Rajanna Sircilla",
    "Kamareddy",
    "Sangareddy",
    "Medak",
    "Siddipet",
    "Jangaon",
    "Yadadri Bhongiri",
    "Medchal-Malkajgiri",
    "Hyderabad",
    "Rangareddy",
    "Vikarabad",
    "Mahabubnagar",
    "Jogulamba Gadwal",
    "Wanaparthy",
    "Nagarkurnool",
    "Nalgonda",
    "Suryapet",
    "Khammam",
    "Mulugu",
    "Narayanpet"
  ];
  static final List<String> DistrictsTelugu = [
    "--ఎంచుకోండి--",
    "ఆదిలాబాద్",
    "కొమరం భీమ్",
    "మంచిర్యాల",
    "నిర్మల్",
    "నిజామాబాద్",
    "జగిత్యాల్",
    "పెద్దపల్లి",
    "జయశంకర్",
    "భద్రాద్రి",
    "మహబూబాబాద్",
    "వరంగల్ రురల్",
    "వరంగల్ అర్బన్",
    "కరీంనగర్",
    "రాజన్న సిరిసిల్ల",
    "కామారెడ్డి",
    "సంగారెడ్డి",
    "మెదక్",
    "సిద్దిపేట",
    "జనగామ",
    "యాదాద్రి బోనగిరి",
    "మేడ్చల్-మల్కాజ్గిరి",
    "హైదరాబాద్",
    "రంగారెడ్డి",
    "వికారాబాద్",
    "మహబూబ్నగర్",
    "జోగులాంబ గద్వాల్",
    "వనపర్తి",
    "నాగర్ కర్నూల్",
    "నల్గొండ",
    "సూర్యాపేట",
    "ఖమ్మం",
    "ములుగు",
    "నారాయణపేట\u200c"
  ];
}
